
name: Publish Storybook

on:
  release:
    types: [created]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build & Deploy Storybook to GitHub pages
        run: |
          npm install
          npm run build-storybook -- -o static_storybook
          cd static_storybook
          echo "style.monday.com" > ./CNAME
          git init
          git config user.name "GH Pages Bot"
          git config user.email "hello@ghbot.com"
          git config commit.gpgsign false
          git add .
          git commit -m "Deploy Storybook [ci-skip]"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Push to Storybook's branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${secrets.GIT_TOKEN}}
          branch: "master:gh-pages"
          force: true
